---
- name: GitHub Enterprise license usage mailer
  hosts: localhost
  gather_facts: true	# required for `ansible_date_time` info

  vars_files:
    - vars/license-mailer.yml

  roles:
    - role: stoe.ghe_license_mailer
