name: Ansible Lint

on:
  push:
    paths:
      - "playbooks/**/*.yml"
  pull_request:
    paths:
      - "playbooks/**/*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
        with:
          targets: |
            playbooks/licemse-mailer/playbook.yml
