name: Ansible Lint

on:
  push:
    paths:
      - playbooks/
  pull_request:
    paths:
      - playbooks/

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: ansible-lint
        uses: ansible/ansible-lint-action@v4
        with:
          targets: |
            playbooks/licemse-mailer/playbook.yml
